### ISSUE TITLE
Option to change the text colour?

### ISSUE THREAD

**Issue by ghjimmy** [context-labs/mactop#1]
When running in a default white terminal, the text is grey on white.  I can change the terrain via the profile for mactop, but would it be possible to change the text to be black so that it's easier to read on a default terminal?

BTW, great program - nice to see that info in a terminal when needed

**Comment by metaspartan** [comment]
Yes, I intend to add more color customization overall and more layouts, will bump this post with the updates in the soon future :)

Thank you for the input!

**Comment by metaspartan** [comment]
e.g. `sudo mactop -c green` color themes have been added! (v0.1.5) Please see the README for information about it. Thanks for the suggestion, since this is now, closing.
