### ISSUE TITLE
Still having P-CPU issues on M2 Max 

### ISSUE THREAD

**Issue by valeriylo** [context-labs/mactop#10]
https://github.com/context-labs/mactop/assets/45401765/c8683c61-f81d-41b2-b994-5c3f57a4a4d8

Latest 0.1.6, same on behaviour after `brew upgrade mactop` from 0.1.5 and after `brew uninstall mactop && brew install mactop`.
New `powermetrics` output is in the attached txt file
[powermetrics_valeriylo.txt](https://github.com/context-labs/mactop/files/15380813/powermetrics_valeriylo.txt)

**Comment by metaspartan** [comment]
The latest fix was only for M3 Max, looks like M2 Max needs the same patch as M3, it is a one line change in the code if you want to test yourself, will get it resolved for v0.1.7, apologies.

https://github.com/context-labs/mactop/blob/main/main.go#L592

Replace this:
```if modelName == "Apple M3 Max" {```

With this:
```if modelName == "Apple M3 Max" || modelName == "Apple M2 Max" {```

I will try to get the patch up this week. Thanks for reporting!

**Comment by metaspartan** [comment]
Give v0.1.7 a shot now, should work 👍

**Comment by valeriylo** [comment]
Yeah, it seems to be fixed now, thanks!
Although, E-CPU & P-CPU update bar is a bit "jittery", not sure if it can be smoothed out. Looking forward new updates!

https://github.com/context-labs/mactop/assets/45401765/94ca2793-0196-4d81-b444-fc2098050334
