### ISSUE TITLE
High CPU use as reported by Activity monitor

### ISSUE THREAD

**Issue by iandol** [context-labs/mactop#13]
I noticed that `mactop` has quite a high CPU use. If I compare `mactop` and `asitop` at the same time and measure with Activity monitor, you can see this stark difference, the python process running asitop uses ~1.5% and mactop is using ~79%.

<img width="757" alt="image" src="https://github.com/context-labs/mactop/assets/153905/aab732be-f7ed-4f48-852f-47380273c168">

I worried it might be some issue with activity monitor, but `htop` shows the same differential (pid 12388 @0.7% vs pid 12342 @89%):

<img width="1056" alt="image" src="https://github.com/context-labs/mactop/assets/153905/95622c51-1968-48fe-9aca-b53b47fe1cb2">

This isn't a contention issue, killing `asitop` and `mactop` still uses the same proportion of CPU.

macbook air M2 + macOS 14.5

**Comment by corkborg** [comment]
I too experience the same problem. (m1 macbook air, m2 macbook pro)
Power consumption seems to increase as CPU increases.

I think it is a very good tool and would like to see it improved.

**Comment by electroly** [comment]
Re: @iandol's comment, I see the same behavior over ssh where the cpu usage is high and proportional to the terminal size. At 271x61, mactop consumes an entire M1 core continuously.

**Comment by Md-Cake** [comment]
I run mactop with cpuprofiler and it seems that the problem is within the ui.Render function calls. I tried to address this in the PR #23. At the very least, I couldn't see a huge difference in the UI performance there, but the CPU usage dropped down to ~1-2% as reported by the activity monitor.

**Comment by electroly** [comment]
I've confirmed the fix in the new release. The CPU usage is now negligible even with large terminal sizes. Nice work!
