### ISSUE TITLE
confirmation that this works on an M1 Pro

### ISSUE THREAD

**Issue by jap** [context-labs/mactop#14]
the text is barely legible with a regular black-on-white terminal, but it seems to work on the M1 Pro on my desk

<img width="1193" alt="Screenshot 2024-05-22 at 08 50 30" src="https://github.com/context-labs/mactop/assets/248953/0884a923-0656-42a3-9265-e7766091ca97">

**Comment by metaspartan** [comment]
We really only support dark backgrounds, try setting your terminal background to black or a darker color for better legibility. Thank you for reporting.

I recommend using https://warp.dev for terminal app
