### ISSUE TITLE
Flickering screen on M1 MacBook Air + macOS14.4.1

### ISSUE THREAD

**Issue by atiorh** [context-labs/mactop#21]
```
% sw_vers
ProductName:		macOS
ProductVersion:		14.4.1
BuildVersion:		23E224
```

https://github.com/context-labs/mactop/assets/64497909/3da3b8ec-293b-47f8-9351-0ba3a0e66460

**Comment by metaspartan** [comment]
This does not look like the correct `mactop` here, the current version is v0.1.7, not sure why it is showing v0.1.11 and the layout looks entirely different than what we offer here? For example, we do not support battery information yet. Please ensure you are installing mactop from the official homebrew repository with `brew install mactop`

**Comment by atiorh** [comment]
oh interesting, you might want to discourage `pip install mactop` if you aren't already:

```
% pip install mactop==
ERROR: Could not find a version that satisfies the requirement mactop== (from versions: 0.1.0, 0.1.4, 0.1.6, 0.1.8, 0.1.9, 0.1.10, 0.1.11)
```
