### ISSUE TITLE
P-Core usage bar overflow on M1 Pro

### ISSUE THREAD

**Issue by laclouis5** [context-labs/mactop#26]
I'm running mactop v0.1.8 on a M1 Pro MacBook Pro and the P-Core Usage bar randomly spikes and overflows to the right of the terminal and the displayed percentage is absurdly hight (above 2000 %) and does not match with any real workload spike on the system (the system is at rest). During those spikes other tools such as top, Activity Monitor or Mx Power Gadget all show a flat and low P-Core usage and frequency.

<img width="871" alt="Screenshot 2024-05-31 at 18 57 09" src="https://github.com/context-labs/mactop/assets/19164542/987c355e-619a-4130-afbb-5bd4cb5c5a1f">

**Comment by metaspartan** [comment]
Fix is up here https://github.com/context-labs/mactop/pull/25 will be merged in for v0.1.9, if you can run the PR locally to confirm it resolves the issue for you, thanks.

**Comment by laclouis5** [comment]
I cloned and switched to the `development` branch and then compiled the program following the instructions but the issue is stil present when launching the program with `sudo ./mactop`. I uninstalled mactop from brew to be sure to launch the right program. The issue seems to spike less often though.

**Comment by metaspartan** [comment]
Okay, interesting, can you please post some of your output from `powermetrics` here, this would also help to assist to see if powermetrics is reporting correctly or if my side of the code. Thank you for debugging 😃

**Comment by laclouis5** [comment]
Here is some powermetrics logs during approximately 10 seconds with a sample rate of 1 second. mactop overflowed during that period of time. Thank you for the quick answer and support!

[powermetrics.log](https://github.com/user-attachments/files/15518677/powermetrics.log)

**Comment by laclouis5** [comment]
A weird thing I noticed is that sometimes `powermetrics` prints this warning/error in between some samples: `Second underflow occured.`.

**Comment by Julien-Ben** [comment]
I second this issue, I encountered the same problem (freshly downloaded from brew)

**Comment by ryul99** [comment]
I have a M1 Pro with 16 GB ram and encountered the same issue.
I dont know why but it seems like this issue doenst happen when mactop is run in tmux session.
FYI, I installed mactop with homebrew.

**Comment by LucasPaivaSilva** [comment]
Same problem here! M1 Pro (base model 2E 6P)

**Comment by RobinBially** [comment]
This isn't fixed, M2 Pro here.

<img width="2297" alt="Bildschirmfoto 2024-10-29 um 08 53 44" src="https://github.com/user-attachments/assets/30e87e09-4204-4152-b2be-6f04067540b6">

**Comment by metaspartan** [comment]
> This isn't fixed, M2 Pro here with v0.1.9 including the #25 patch
> 
> <img alt="Bildschirmfoto 2024-10-29 um 08 53 44" width="2000" src="https://private-user-images.githubusercontent.com/7304732/381030550-30e87e09-4204-4152-b2be-6f04067540b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMTExODgsIm5iZiI6MTczMTExMDg4OCwicGF0aCI6Ii83MzA0NzMyLzM4MTAzMDU1MC0zMGU4N2UwOS00MjA0LTQxNTItYjJiZS02ZjA0MDY3NTQwYjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDlUMDAwODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWM5ZWEzYjlkYzZlNGM3MDM2ZGVhMzgwZWZmODBkY2U2YjcyZTBlYWRmNDMzNWM4MDY4ODNmZDRhZWNkZDU1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.oxqqj1uXFbIyKntJXiNXsuq8CcVDbkw3jWxEEYdfd5w">

Apologies for the late reply, please try to manually build the development branch (v0.2.0) I am working on doing a manual workaround for calculating certain M series chips P and E core usage, due to Apple's powermetrics having a bug/issue, if you are having the issue above, please post your `powermetrics` output in a text file, as it can help me validate calculations.

**Comment by metaspartan** [comment]
Just resolved this in v0.2.0, will close this once I get a few confirmations.

**Comment by RobinBially** [comment]
The values reported in mactop match those in powermetrics, but they seem far too high. Even when idle, both P-cores and E-cores are consistently at 50–70%.

In contrast, the values shown in Activity Monitor and iStat Menus are much lower, around 3–4%.

**Comment by metaspartan** [comment]
Thanks for testing, yea, the next set of updates we are moving to the direct macOS API via cgo to get individual E and P Core usage values along with total usage percent. Powermetrics seems just buggy and inconsistent across devices, moving to this new way soon will make us more inline with Activity Monitor, htop, etc.

**Comment by johnalanwoods** [comment]
May I ask which API? This sounds great.

**Comment by metaspartan** [comment]
> May I ask which API? This sounds great.

The `host_processor_info` within Cgo, which is the same as `htop` and similar to what Activity Monitor and others utilize, I will put the implementation up into the `development` branch later tonight 😎

**Comment by johnalanwoods** [comment]
Fantastic!

**Comment by metaspartan** [comment]
https://github.com/context-labs/mactop/pull/37 it is up in the `development` branch if you wish to test it out! 👍 🍻

**Comment by metaspartan** [comment]
CPU usage was revamped and is now using Apple's native mach kernel API as of v0.2.2 of mactop, Closing this. Please update!

**Comment by Julien-Ben** [comment]
@metaspartan
