### ISSUE TITLE
Unable to install on M2 Mac Mini

### ISSUE THREAD

**Issue by ari-vedant-jain** [context-labs/mactop#27]
Get the following error, when trying to install using 
`brew install mactop`
```
mactop: The arm64 architecture is required for this software.
Error: mactop: An unsatisfied requirement failed this build.
```

**Comment by johnalanwoods** [comment]
You need Apple Si.

**Comment by ari-vedant-jain** [comment]
Thanks for your response!
Is M2 processor on Apple Mac Mini not Apple Si?

**Comment by metaspartan** [comment]
M2 is supported and Apple Silicon, you maybe need to ensure you aren't running `brew install mactop` in a Rosetta terminal.

**Comment by ari-vedant-jain** [comment]
Ok, so it's not clear in the README that you need Golang installed even if you're using Homebrew. Docs need a step before ```brew install mactop```

**Comment by xxrjun** [comment]
I encountered the same installation issue on my M2 MacBook Pro while trying to install mactop.

Here's the command and the error message I received:

```bash
(base) ➜  ~ brew install mactop
mactop: The arm64 architecture is required for this software.
Error: mactop: An unsatisfied requirement failed this build.
```

To confirm my architecture, I ran the following commands:

```bash
(base) ➜  ~ uname -m
arm64
(base) ➜  ~ arch
arm64
```

Both confirm that my machine is indeed arm64. However, despite this, the installation still fails. I also checked the information for mactop:

```bash
(base) ➜  ~ brew info mactop
==> mactop: stable 0.1.8
Apple Silicon Monitor Top written in Golang
https://github.com/context-labs/mactop
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/m/mactop.rb
License: MIT
==> Dependencies
Build: go ✘
==> Requirements
Required: arm64 architecture ✘, macOS ✔
==> Caveats
mactop requires root privileges, so you will need to run `sudo mactop`.
You should be certain that you trust any software you grant root privileges.
==> Analytics
install: 165 (30 days), 1,350 (90 days), 1,350 (365 days)
install-on-request: 165 (30 days), 1,350 (90 days), 1,350 (365 days)
build-error: 0 (30 days)
```
