### ISSUE TITLE
Does this show memory pressure?

### ISSUE THREAD

**Issue by YousufSSyed** [context-labs/mactop#3]
It would be nice to replace Activity Monitor with this but what I like is its Memory Pressure graph:

![CleanShot 2024-05-03 at 07 57 29@2x](https://github.com/context-labs/mactop/assets/42646062/8af67f8b-4654-4a6a-b8eb-286d3ca99a06)

**Comment by metaspartan** [comment]
Yes it shows memory in-use and memory swap information, closing this for now.

**Comment by YousufSSyed** [comment]
@metaspartan Can it show a graph like Activity Monitor does?

**Comment by metaspartan** [comment]
> @metaspartan Can it show a graph like Activity Monitor does?

Yea would be possible to display it in a timed data set, though we are out of space in the current layout, so would require a swapping mode, very doable, possibility to be added in future.
