### ISSUE TITLE
Can't Run, Install, Build on M1 MBP

### ISSUE THREAD

**Issue by timscodebase** [context-labs/mactop#32]
What does this not work on my M1 MBP?

![Screenshot 2024-10-25 at 12 26 58 AM](https://github.com/user-attachments/assets/5e105de0-9e3f-4a84-94c7-5df885b8b0e7)
![Screenshot 2024-10-25 at 12 24 08 AM](https://github.com/user-attachments/assets/df2033bb-52ae-4275-98c1-77e8097ea152)

**Comment by timscodebase** [comment]
![Screenshot 2024-10-25 at 12 30 34 AM](https://github.com/user-attachments/assets/272b9132-be0c-457d-bd36-7238e0e962f0)

**Comment by metaspartan** [comment]
Reinstall homebrew in a terminal that you ensure is not Rosetta enabled (Get Info on Terminal.app) Its trying to install it under the emulated Rosetta x64 arch vs arm64 (M series chips)
