### ISSUE TITLE
Great project - ANE?

### ISSUE THREAD

**Issue by johnalanwoods** [context-labs/mactop#38]
Very cool project, what about the ANE (Neural engine), is it something this project is interested in?

**Comment by metaspartan** [comment]
Thank you! Apple's neural engine (ANE) is not available for serious developers and no application currently supports it, when or if they do, it can easily be added back, but until then, there is no point in having it as never in use, so it was removed in the last update. Most all AI applications currently only use Apple's Metal API for the GPU.

**Comment by tverboon** [comment]
Image Playground on macOS 15.2 is using ANE up to 3900 mW during image generation.

**Comment by metaspartan** [comment]
Yea, I will be adding this back in, probably within another optional layout, thanks!

**Comment by johnalanwoods** [comment]
@metaspartan that would be great! Seem the ANE is finally utilised.

**Comment by shashankprasanna** [comment]
+1 for ANE. Thanks for your hard work on mactop. I was surprised to see it go when I updated mactop. ANE is used by default for models compiled using CoreML, and most of the models here use it: https://huggingface.co/apple. Would love to see it included again, thanks!

**Comment by metaspartan** [comment]
Yup, hopefully will have it back in next update this weekend! Cheers!

**Comment by johnalanwoods** [comment]
@metaspartan - wondering if you'd accept a PR on ANE if I pushed it?

**Comment by metaspartan** [comment]
Yea depending on how its implemented, ANE has no way of actually reading the data from the way I understand it, asitop is just using an estimate based off the wattage used, which is inaccurate.

**Comment by demiliani** [comment]
Why not adding an option to remove ANE for people that don't need this value?

**Comment by metaspartan** [comment]
> Why not adding an option to remove ANE for people that don't need this value?

You can simply change layouts to a different layout, ANE is accurately calculated now, so its here to stay. More layouts will be coming too! (You can swap by pressing "L" in mactop)
