### ISSUE TITLE
Panic: index out of range (caused by missing interval value)

### ISSUE THREAD

**Issue by val-ki** [context-labs/mactop#7]
STR:
sudo ./mactop --interval

----
Actual result:
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
main.main()
        /Users/user/Work/mactop/main.go:348 +0x120f

----
``` go
/* 347 */ if len(os.Args) > 1 && os.Args[1] == "--interval" ... 
/* 348 */     interval, err := strconv.Atoi(os.Args[2])
```

**Comment by metaspartan** [comment]
You must include a interval speed number

e.g. `sudo mactop --interval 2000`
